# List of Commands into a class
from dv1 import Command

class Commands:
    def __init__():
        #whole command list here
        rf = Command("RF", "", "Fréquence")
        zp = Command("ZP", "", "Allumage")
        qp = Command("QP", "", "Eteindre") #result code 10?
        ag = Command("AG", "", "Audio Gain")
        st = Command("ST", "", "Freq step")
        sh = Command("SH", "", "Freq step adjust")
        md = Command("MD", "", "Mode")
        zj = Command("ZJ", "", "Précédent")
        zk = Command("ZK", "", "Suivant")
        ex = Command("EX", "", "Stopper le remote control")
        sq = Command("SQ", "", "Sélection du squelch")
        nq = Command("NQ", "", "Valeur du Noise squelch")
        lq = Command("LQ", "", "Valeur du Level squelch")
        vq = Command("VQ", "", "Voice squelch")
        ci = Command("CI", "", "Activer le CTCSS")
        cn = Command("CN", "", "Selection du ton")
        di = Command("DI", "", "DCS ON/OFF")
        ds = Command("DS", "", "Code DCS")
        dc = Command("DC", "", "Digital CR code")
        dj = Command("DJ", "", "Sortie DATA")
        dk = Command("DK", "", "Charger le dernier message")
        ac = Command("AC", "", "AGC")
        rg = Command("RG", "", "Gain manuel")
        ifn = Command("IF", "", "Bande passante IF")
        ls = Command("LS", "", "Auto Notch")
        nr = Command("NR", "", "Noise Reduction")
        of = Command("OF", "", "Offset RX")
        ol = Command("OL", "", "Offset freq")
        ox = Command("OX", "", "Monitor Offset")
        po = Command("PO", "", "Priority receive")
        pp = Command("PP", "", "Priority receive channel")
        ti = Command("TI", "", "Priority receive interval")
        sc = Command("SC", "", "Descrambler frequency")
        si = Command("SI", "", "Descrambler ON/OFF")
        dl = Command("DL", "", "Delay time")
        fr = Command("FR", "", "Free time")
        dt = Command("DT", "", "System clock")
        sp = Command("SP", "", "Sleep timer")
        tr = Command("TR", "", "Recording timer")
        bp = Command("BP", "", "Beep")
        lb = Command("LB", "", "Backlight")
        ld = Command("LD", "", "Dimmer")
        kl = Command("KL", "", "Key backlight color")
        ln = Command("LN", "", "Contrast")
        pt = Command("PT", "", "Write protect")
        zi = Command("ZI", "", "Receiver ID")
		lc = Command("LC", "", "Frequency data output")

